#!/usr/bin/ash
# Script defines WAN parameters for VPNA and Router.
# According to the network changes will be reconfigured WEB server, SSH
# and privoxy.

[ wan = "$INTERFACE" ] && {
	[ "$(uci get sabai.vpn.proto)" = "pptp" ] && exit 0
	logger -t SABAI.WAN "Network data of $DEVICE will be updated."
	[ "$(uci get -p /var/state/ network.wan.up)" = 1 ] && {
		ip_wan="$(ifconfig -a eth0 | grep -F "inet addr" | awk '{print $2}' | tr -d 'addr:')"
		gateway_wan="$( route -n | grep eth0 | grep "UG" | awk '{print $2}')"
		mask_wan="$( route -n | grep eth0 | grep "UH" | awk '{print $3}')"

		uci set network.wan.ipaddr=$ip_wan
		uci set network.wan.gateway=$gateway_wan
		uci set network.wan.netmask=$mask_wan
		uci commit network

		[ $(uci get sabai.wan.factory_mac) ] || /www/bin/wan.sh set_mac
		uci set sabai.wan.ipaddr=$ip_wan
		uci set sabai.wan.gateway=$gateway_wan
		uci set sabai.wan.netmask=$mask_wan
		uci commit sabai
	}
	/etc/init.d/dropbear restart
}
